# Generated by Django 3.1.7 on 2021-04-07 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ManyToManyField(related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
