# Generated by Django 3.1.7 on 2021-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210412_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='analyze_path',
        ),
        migrations.RemoveField(
            model_name='game',
            name='path',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='game',
            name='result',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
