name: deploy

on: 
  push:
    branches:
      - main

jobs:
  deliver-main:
    runs-on: ubuntu-latest
    env:
      path: /var/www/

    steps:
      #- name: stop server during deployment
        #run: sudo sv stop nginx

      - name: checkout main branch
        uses: actions/checkout@v2
        #with:
          #ref: develop
          #in case we want to deploy a certain branch (ex : serve main and develop at different points)
          
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Ajout clé SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.PRIV_KEY }}

      - name: Add know Host
        run: ssh-keyscan -p ${{ secrets.DEPLOY_HOST_SSH_PORT }} ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
